// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartCity_BE.Data;

#nullable disable

namespace Smartcity_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251101185252_AddBusRouteSeedData")]
    partial class AddBusRouteSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RouteName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RouteNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Schedule")
                        .HasColumnType("ntext");

                    b.HasKey("Id");

                    b.ToTable("BusRoutes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RouteName = "Vũng Tàu – Phú Túc (Đồng Nai)",
                            RouteNumber = "22",
                            Schedule = "5:00 - 18:00"
                        },
                        new
                        {
                            Id = 2,
                            RouteName = "Vũng Tàu – Phú Mỹ",
                            RouteNumber = "6",
                            Schedule = "5:30 - 18:30"
                        },
                        new
                        {
                            Id = 3,
                            RouteName = "Vũng Tàu – Bình Châu",
                            RouteNumber = "4",
                            Schedule = "5:00 - 17:30"
                        },
                        new
                        {
                            Id = 4,
                            RouteName = "Xuyên Mộc – Dầu Giây (Đồng Nai)",
                            RouteNumber = "15",
                            Schedule = "6:00 - 18:00"
                        },
                        new
                        {
                            Id = 5,
                            RouteName = "Bình Châu – Bình Thuận",
                            RouteNumber = "8",
                            Schedule = "5:45 - 17:45"
                        },
                        new
                        {
                            Id = 6,
                            RouteName = "Quốc Lộ 51 – Ngã Tư Vũng Tàu",
                            RouteNumber = "611 (cũ)",
                            Schedule = "5:00 - 18:00"
                        },
                        new
                        {
                            Id = 7,
                            RouteName = "Vũng Tàu – Ngã Tư Vũng Tàu",
                            RouteNumber = "611 (mới)",
                            Schedule = "5:30 - 18:30"
                        },
                        new
                        {
                            Id = 8,
                            RouteName = "Long Điền – Đồng Nai",
                            RouteNumber = "606",
                            Schedule = "5:15 - 18:15"
                        });
                });

            modelBuilder.Entity("NguoiDung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("PhanAnh", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("HinhAnhUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<long>("NguoiDungId")
                        .HasColumnType("bigint");

                    b.Property<string>("NoiDung")
                        .HasColumnType("ntext");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("PhanAnh");
                });

            modelBuilder.Entity("PhanAnh", b =>
                {
                    b.HasOne("NguoiDung", "NguoiDung")
                        .WithMany("DanhSachPhanAnh")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("NguoiDung", b =>
                {
                    b.Navigation("DanhSachPhanAnh");
                });
#pragma warning restore 612, 618
        }
    }
}
